### ISSUE TITLE
Unable to run on MAC

### ISSUE THREAD

**Issue by bibibo-77** [Einswilli/KivymdStudio#12]
Hello, could You help with this issue ?

file:///Users/peter/Downloads/KivymdStudio-master/qml/NewProject.qml:540:17: QML ScrollView: Binding loop detected for property "implicitHeight"
libpng warning: iCCP: known incorrect sRGB profile
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fc4e3aeae90'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff810026fa6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80fb1b231 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8100cc2a4 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff80ff94863 ___forwarding___ + 1379
	4   CoreFoundation                      0x00007ff80ff94278 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000013433e1f2 TkpInit + 408
	6   libtk8.6.dylib                      0x00000001342adaac Initialize + 2454
	7   _tkinter.cpython-39-darwin.so       0x0000000133f976d4 Tcl_AppInit + 84
	8   _tkinter.cpython-39-darwin.so       0x0000000133f96ff2 _tkinter_create + 1362
	9   Python                              0x0000000107850143 cfunction_vectorcall_FASTCALL + 195
	10  Python                              0x00000001078e9eec call_function + 732
	11  Python                              0x00000001078e7382 _PyEval_EvalFrameDefault + 25554
	12  Python                              0x00000001078eabe3 _PyEval_EvalCode + 2611
	13  Python                              0x0000000107811dd1 _PyFunction_Vectorcall + 289
	14  Python                              0x0000000107811535 _PyObject_FastCallDictTstate + 293
	15  Python                              0x00000001078120b8 _PyObject_Call_Prepend + 152
	16  Python                              0x000000010786bb15 slot_tp_init + 165
	17  Python                              0x0000000107867069 type_call + 345
	18  Python                              0x00000001078116d7 _PyObject_MakeTpCall + 359
	19  Python                              0x00000001078e9f7c call_function + 876
	20  Python                              0x00000001078e7382 _PyEval_EvalFrameDefault + 25554
	21  Python                              0x0000000107811e48 function_code_fastcall + 104
	22  Python                              0x0000000107813ed2 method_vectorcall + 274
	23  libpyside2.abi3.5.15.dylib          0x00000001074c7576 _ZN6PySide13SignalManager20callPythonMetaMethodERK11QMetaMethodPPvP7_objectb + 534
	24  libpyside2.abi3.5.15.dylib          0x00000001074c6fa7 _ZN6PySide13SignalManager11qt_metacallEP7QObjectN11QMetaObject4CallEiPPv + 519
	25  QtQml                               0x000000010b32661d _ZL10CallMethodRK18QQmlObjectOrGadgetiiiPiPN3QV415ExecutionEngineEPNS3_8CallDataEN11QMetaObject4CallE + 5613
	26  QtQml                               0x000000010b322662 _ZL11CallPreciseRK18QQmlObjectOrGadgetRK16QQmlPropertyDataPN3QV415ExecutionEngineEPNS5_8CallDataEN11QMetaObject4CallE + 418
	27  QtQml                               0x000000010b321fda _ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i + 1418
	28  QtQml                               0x000000010b33c7d5 _ZN3QV44Moth3VME9interpretEPNS_13CppStackFrameEPNS_15ExecutionEngineEPKc + 4469
	29  QtQml                               0x000000010b33b542 _ZN3QV44Moth3VME4execEPNS_13CppStackFrameEPNS_15ExecutionEngineE + 130
	30  QtQml                               0x000000010b2e1985 _ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE + 341
	31  QtQml                               0x000000010b465b9e _ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb + 622
	32  QtQml                               0x000000010b41c3f6 _ZN25QQmlBoundSignalExpression8evaluateEPPv + 1014
	33  QtQml                               0x000000010b41cbcb _Z24QQmlBoundSignal_callbackP20QQmlNotifierEndpointPPv + 427
	34  QtQml                               0x000000010b44b785 _ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv + 581
	35  QtCore                              0x000000010baedb88 _Z10doActivateILb0EEvP7QObjectiPPv + 120
	36  QtQml                               0x000000010b48114d _ZN17QQmlObjectCreator8finalizeER26QQmlInstantiationInterrupt + 1533
	37  QtQml                               0x000000010b4114a2 _ZN20QQmlComponentPrivate8completeEP17QQmlEnginePrivatePNS_17ConstructionStateE + 82
	38  QtQml                               0x000000010b40f2e2 _ZN20QQmlComponentPrivate14completeCreateEv + 322
	39  QtQml                               0x000000010b410bd7 _ZN13QQmlComponent6createEP11QQmlContext + 71
	40  QtQml                               0x000000010b46ff4a _ZN28QQmlApplicationEnginePrivate10finishLoadEP13QQmlComponent + 474
	41  QtQml                               0x000000010b46fd60 _ZN28QQmlApplicationEnginePrivate9startLoadERK4QUrlRK10QByteArrayb + 720
	42  QtQml                               0x000000010b4707ed _ZN21QQmlApplicationEngine4loadERK7QString + 93
	43  QtQml.abi3.so                       0x0000000107fab7a2 _ZL34Sbk_QQmlApplicationEngineFunc_loadP7_objectS0_ + 130
	44  Python                              0x00000001078503da cfunction_vectorcall_O + 202
	45  Python                              0x00000001078e9eec call_function + 732
	46  Python                              0x00000001078e7382 _PyEval_EvalFrameDefault + 25554
	47  Python                              0x0000000107811e48 function_code_fastcall + 104
	48  Python                              0x0000000107813e8a method_vectorcall + 202
	49  Python                              0x00000001078e9eec call_function + 732
	50  Python                              0x00000001078e7382 _PyEval_EvalFrameDefault + 25554
	51  Python                              0x00000001078eabe3 _PyEval_EvalCode + 2611
	52  Python                              0x00000001078e0e8b PyEval_EvalCode + 139
	53  Python                              0x0000000107934dc3 pyrun_file + 387
	54  Python                              0x00000001079330f2 PyRun_SimpleFileExFlags + 850
	55  Python                              0x00000001079501d9 Py_RunMain + 1801
	56  Python                              0x000000010795066f pymain_main + 223
	57  Python                              0x000000010795086b Py_BytesMain + 43
	58  dyld                                0x00007ff80fb4f386 start + 1942
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      python studio.py

**Comment by Einswilli** [comment]
`NSInvalidArgumentException Error`: This error is specific to `Objective-C` and appears to indicate that an unrecognized method has been called. It may be related to the integration of `Python, Qt, and Objective-C`. Ensure that you are using compatible versions of all libraries and dependencies,.
Using Docker can help you avoid this issue.

**Comment by bibibo-77** [comment]
Hello, thanks for your answer.  I tried to use Docker but I was not successful. Maybe I do not know how to use Docker.
First I used command  "docker build path_to_folder_kivystudio" and than command "docker run name_of_image" After that I got an error something like  "no desktop".

**Comment by Einswilli** [comment]
Try this
`sudo xhost +`
`sudo docker build -t kvs-code .`
`docker run -it --rm --env DISPLAY=$DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix kvs-code`
`sudo docker run -it --rm --env DISPLAY=$DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/einswilli/KivymdStudio:/kvstudio kvs-code`

**Comment by bibibo-77** [comment]
hello, I would like to ask you, what is it kvs-code at the end of last two commands ? Is it name of folder kivyStudio ?

`docker run -it --rm --env DISPLAY=$DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix kvs-code`

`sudo docker run -it --rm --env DISPLAY=$DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/einswilli/KivymdStudio:/kvstudio kvs-code`

**Comment by bibibo-77** [comment]
Hi, so I used name:tag instead kvs-code but an error appears.

qt.qpa.xcb: could not connect to display /private/tmp/com.apple.launchd.W1w7pf96oz/org.macosforge.xquartz:0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

**Comment by Einswilli** [comment]
Make sure you have `XQuartz` installed:

- You can download XQuartz from the official website: [https://www.xquartz.org/](https://www.xquartz.org/)
- Install XQuartz and restart your system if necessary.

Run Docker commands with XQuartz:

 To allow connection to the X server (XQuartz), you need to execute the following command:
   ```shell
   xhost + 127.0.0.1
   ```

**Comment by bibibo-77** [comment]
Hello, I solved my problem.  In the end I used the Python3.10 in venv. Currently it works good.

**Comment by Einswilli** [comment]
Cool!
You can add your solution and close the issue .
Thanks 👍
